# Generated by Django 3.2.4 on 2022-05-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user1_last_read_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user1_last_unread_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user1_unread',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2_last_read_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2_last_unread_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2_unread',
            field=models.IntegerField(default=0),
        ),
    ]
